name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: 0.19.0

    - name: Install Arduino core
      run: arduino-cli core install arduino:avr

    - name: Install dependencies
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile Sketch
      run: arduino-cli compile --fqbn arduino:avr:uno C:\\EmbeddedDevelopment\\devops_training\\src\\src\\main.cpp

    - name: Upload Sketch (optional)
      if: github.event_name == 'push'
      run: arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno C:\\EmbeddedDevelopment\\devops_training\\src\\src\\main.cpp
      env:
        ARDUINO_UPLOAD_PORT: ${{ secrets.ARDUINO_UPLOAD_PORT }}