name: CI/CD Pipeline for C Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install GCC (C Compiler)
      - name: Install GCC
        run: sudo apt-get install build-essential

      # Step 3: Change directory
      - name: Change to src directory
        run: cd devops_training/src

      # Step 4: Compile the C program
      - name: Compile program
        run: gcc -g -o assembler.exe assembler.c parser.c symbol_table.c filehandling.c

      # Step 5: Run tests
      - name: Run tests
        run: ./my_program