name: PlatformIO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio
      
      - name: Clean PlatformIO build
        run: pio run --target clean
      
      - name: Ensure unity_config.h exists
        run: |
          if [ ! -f include/unity_config.h ]; then
            echo "Error: unity_config.h is missing!" 
            exit 1
          fi

      - name: Copy unity_config.h into Unity library folder
        run: |
          mkdir -p .pio/libdeps/uno/Unity/src/
          cp include/unity_config.h .pio/libdeps/uno/Unity/src/unity_config.h

      - name: Build with PlatformIO
        run: pio run

      - name: Rename firmware with date
        run: |
          DATE=$(date +"%y%m%d")
          cp .pio/build/uno/firmware.hex "${DATE}_Firmware.hex"
          echo "FIRMWARE_FILE=${DATE}_Firmware.hex" >> $GITHUB_ENV

      - name: Upload all PlatformIO build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: platformio-build-artifacts
          path: .pio/build/uno/*
  test:
      runs-on: ubuntu-latest
      needs: build # Ensures testing runs AFTER building
      steps:
        - uses: actions/checkout@v4

        - name: Install PlatformIO
          run: pip install platformio

        - name: Upload Unit Tests
          run: pio test -e uno --without-testing
        
        - name: Run Unit Tests
          run: pio device monitor

        - name: Check Test Results
          run: |
            if grep -q "FAIL" .pio/test_output.log; then
              echo "Tests failed!"
              exit 1
            fi